"""
manual_priors_2026_27.py — Hand-derived Bayesian priors for the Premier League model.

Generated by priors/2026_27_priors.ipynb from three blended sources:
  1. 2025-26 season posterior (att_str/def_str) for the 17 teams staying up.
  2. This season's Transfermarkt squad value regressed against non-penalty PL
     goals-for/against rate (117 historical team-seasons, R²=0.56 attack /
     0.40 defense), for all 20 teams -- weight 33%.
  3. Championship-form PL forecast (champ_analysis.ipynb's promotion-effect
     model) for Hull, Coventry and Ipswich, in place of a posterior they don't have.

Sources 1/3 get weight 67%, source 2 gets 33%. Promoted sides use
wider sigma=0.3 to reflect greater uncertainty; established PL sides use
sigma=0.25. Relegated (real, penalty-inclusive 2025-26 table): Burnley, West Ham, Wolves.

Values are the raw (pre-normalisation) mu estimates. The model normalises them
at runtime by subtracting the mean across all teams, ensuring the priors sum to
zero (identifiability constraint).

Usage
-----
    from manual_priors_2026_27 import MANUAL_ATT_PRIORS, MANUAL_DEF_PRIORS
    _, trace = build_and_sample_model(
        df, n_teams, team_mapping=team_mapping,
        manual_att_priors=MANUAL_ATT_PRIORS,
        manual_def_priors=MANUAL_DEF_PRIORS,
    )
"""

import numpy as np

# ── Raw priors (pre-normalisation) ───────────────────────────────────────────

_RAW_ATT = {
             'Arsenal': (0.294, 0.25),
         'Aston Villa': (0.056, 0.25),
         'Bournemouth': (0.113, 0.25),
           'Brentford': (0.067, 0.25),
            'Brighton': (0.099, 0.25),
             'Chelsea': (0.233, 0.25),
      'Crystal Palace': (-0.011, 0.25),
             'Everton': (-0.032, 0.25),
              'Fulham': (-0.115, 0.25),
               'Leeds': (-0.036, 0.25),
           'Liverpool': (0.249, 0.25),
            'Man City': (0.369, 0.25),
          'Man United': (0.233, 0.25),
           'Newcastle': (0.083, 0.25),
        'Nottm Forest': (-0.018, 0.25),
          'Sunderland': (-0.213, 0.25),
           'Tottenham': (0.025, 0.25),
    # Promoted sides — wider prior
                'Hull': (-0.586, 0.3),
            'Coventry': (-0.208, 0.3),
             'Ipswich': (-0.231, 0.3),
}

_RAW_DEF = {
             'Arsenal': (-0.418, 0.25),
         'Aston Villa': (0.069, 0.25),
         'Bournemouth': (0.053, 0.25),
           'Brentford': (0.010, 0.25),
            'Brighton': (-0.049, 0.25),
             'Chelsea': (-0.060, 0.25),
      'Crystal Palace': (0.022, 0.25),
             'Everton': (0.082, 0.25),
              'Fulham': (0.071, 0.25),
               'Leeds': (0.077, 0.25),
           'Liverpool': (-0.072, 0.25),
            'Man City': (-0.184, 0.25),
          'Man United': (-0.042, 0.25),
           'Newcastle': (0.027, 0.25),
        'Nottm Forest': (0.047, 0.25),
          'Sunderland': (0.082, 0.25),
           'Tottenham': (0.013, 0.25),
    # Promoted sides — wider prior
                'Hull': (0.585, 0.3),
            'Coventry': (0.343, 0.3),
             'Ipswich': (0.335, 0.3),
}


def _normalise(raw):
    """Subtract mean of mus so priors sum to zero (identifiability)."""
    teams = list(raw.keys())
    mus   = np.array([raw[t][0] for t in teams])
    mus  -= mus.mean()
    sigs  = np.array([raw[t][1] for t in teams])
    return {t: (float(mus[i]), float(sigs[i])) for i, t in enumerate(teams)}


MANUAL_ATT_PRIORS = _normalise(_RAW_ATT)
MANUAL_DEF_PRIORS = _normalise(_RAW_DEF)
