"""
manual_priors_2026_27.py — Hand-derived Bayesian priors for the Premier League model.

Generated by priors/2026_27_priors.ipynb from three blended sources:
  1. 2025-26 season posterior (att_str/def_str) for the 17 teams staying up.
  2. This season's Transfermarkt squad value regressed against non-penalty PL
     goals-for/against rate (117 historical team-seasons, R²=0.56 attack /
     0.40 defense), for all 20 teams -- weight 33%.
  3. Championship-form PL forecast (champ_analysis.ipynb's promotion-effect
     model) for Hull, Coventry and Ipswich, in place of a posterior they don't have.

Sources 1/3 get weight 67%, source 2 gets 33%. Sigma is hand-set, not
auto-derived by this notebook -- regenerating this file only touches the mu values, sigma is
preserved from whatever's already here (see the file-writer cell in priors/2026_27_priors.ipynb
for the fallback used when a team has no existing entry yet). Relegated (real, penalty-inclusive
2025-26 table): Burnley, West Ham, Wolves.

Values are the raw (pre-normalisation) mu estimates. The model normalises them
at runtime by subtracting the mean across all teams, ensuring the priors sum to
zero (identifiability constraint).

Usage
-----
    # Mid-season (recommended): sigma ramps from ~half the values below at
    # GW1 up to the full values by GW10 -- see scaled_priors().
    from manual_priors_2026_27 import scaled_priors
    att_priors, def_priors = scaled_priors(games_played)
    _, trace = build_and_sample_model(
        df, n_teams, team_mapping=team_mapping,
        manual_att_priors=att_priors,
        manual_def_priors=def_priors,
    )

    # Season-target sigma directly, no ramp (e.g. preseason projections):
    from manual_priors_2026_27 import MANUAL_ATT_PRIORS, MANUAL_DEF_PRIORS
"""

import numpy as np

# ── Raw priors (pre-normalisation) ───────────────────────────────────────────

_RAW_ATT = {
             'Arsenal': (0.257, 0.3),
         'Aston Villa': (0.046, 0.3),
         'Bournemouth': (0.084, 0.4),
           'Brentford': (0.041, 0.3),
            'Brighton': (0.064, 0.4),
             'Chelsea': (0.177, 0.4),
      'Crystal Palace': (-0.029, 0.3),
             'Everton': (-0.092, 0.3),
              'Fulham': (-0.119, 0.3),
               'Leeds': (-0.070, 0.3),
           'Liverpool': (0.221, 0.3),
            'Man City': (0.335, 0.3),
          'Man United': (0.209, 0.4),
           'Newcastle': (0.061, 0.4),
        'Nottm Forest': (-0.060, 0.4),
          'Sunderland': (-0.227, 0.4),
           'Tottenham': (-0.007, 0.4),
    # Promoted sides — wider prior
                'Hull': (-0.519, 0.5),
            'Coventry': (-0.292, 0.5),
             'Ipswich': (-0.293, 0.5),
}

_RAW_DEF = {
             'Arsenal': (-0.442, 0.3),
         'Aston Villa': (0.024, 0.3),
         'Bournemouth': (0.020, 0.4),
           'Brentford': (-0.024, 0.3),
            'Brighton': (-0.078, 0.4),
             'Chelsea': (-0.062, 0.4),
      'Crystal Palace': (-0.019, 0.3),
             'Everton': (0.067, 0.3),
              'Fulham': (0.026, 0.3),
               'Leeds': (0.047, 0.3),
           'Liverpool': (-0.107, 0.3),
            'Man City': (-0.212, 0.3),
          'Man United': (-0.080, 0.4),
           'Newcastle': (-0.011, 0.4),
        'Nottm Forest': (0.023, 0.4),
          'Sunderland': (0.041, 0.4),
           'Tottenham': (-0.018, 0.4),
    # Promoted sides — wider prior
                'Hull': (0.448, 0.5),
            'Coventry': (0.244, 0.5),
             'Ipswich': (0.229, 0.5),
}


def _normalise(raw):
    """Subtract mean of mus so priors sum to zero (identifiability)."""
    teams = list(raw.keys())
    mus   = np.array([raw[t][0] for t in teams])
    mus  -= mus.mean()
    sigs  = np.array([raw[t][1] for t in teams])
    return {t: (float(mus[i]), float(sigs[i])) for i, t in enumerate(teams)}


MANUAL_ATT_PRIORS = _normalise(_RAW_ATT)
MANUAL_DEF_PRIORS = _normalise(_RAW_DEF)


# ── Early-season sigma ramp ───────────────────────────────────────────────────
# The sigmas above are a season-long target, calibrated against how much a team's strength
# genuinely varies season-to-season. Applied unchanged from GW1, they're too loose relative
# to how little real match data exists yet -- one extreme early scoreline swings a rating
# almost as much as it would mid-season. Empirically swept against 2025-26's actual final
# posterior: the RMSE-optimal sigma rises smoothly from ~half the season target at GW1 to
# the full target by GW10, so ramp sigma over that window rather than applying the season
# value from kickoff.
def sigma_ramp_scale(games_played: int, ramp_games: int = 10, start_fraction: float = 0.4) -> float:
    """
    Fraction of season-target sigma to use, given games played so far.

    Ramps linearly from `start_fraction` (of the season-target sigma) at zero
    games played, up to 1.0 (full season-target sigma) by `ramp_games` games
    played, then stays at 1.0 for the rest of the season.
    """
    if ramp_games <= 0:
        return 1.0
    progress = min(max(games_played, 0), ramp_games) / ramp_games
    return start_fraction + (1.0 - start_fraction) * progress


def scaled_priors(games_played: int, ramp_games: int = 10, start_fraction: float = 0.4):
    """
    Return (att_priors, def_priors) with sigma scaled per the early-season
    ramp -- mu is untouched. Use this instead of MANUAL_ATT_PRIORS /
    MANUAL_DEF_PRIORS directly when fitting mid-season, so early gameweeks
    aren't overreacting to a handful of results.
    """
    scale = sigma_ramp_scale(games_played, ramp_games, start_fraction)
    att = {t: (mu, sigma * scale) for t, (mu, sigma) in MANUAL_ATT_PRIORS.items()}
    defn = {t: (mu, sigma * scale) for t, (mu, sigma) in MANUAL_DEF_PRIORS.items()}
    return att, defn


# ── Global (home_adv/baseline) priors and their early-season ramp ────────────
# Recency-weighted (0.6**seasons_ago) empirical estimate from np_matches over the last 5
# *completed* seasons (see this notebook's section 1 -- TARGET_SEASON is deliberately
# excluded from that computation: it's what's being forecast, not a completed season to
# learn the league constant from).
HOME_ADV_PRIOR_MU = 0.1634
HOME_ADV_PRIOR_SIGMA = 0.1
BASELINE_PRIOR_MU = 0.2077
BASELINE_PRIOR_SIGMA = 0.1

# ── Jensen correction ─────────────────────────────────────────────────────────
# BASELINE_PRIOR_MU above is calibrated to the *neutral* team (att_str=def_str=0) rate. But
# home_lam/away_lam use exp(baseline + ... + att_str[i] + def_str[j]), and exp() is convex --
# so averaging over real, unequal teams (this season's own MANUAL_ATT_PRIORS/MANUAL_DEF_PRIORS
# spread) pushes the *league-average* predicted goal rate above the neutral-team rate
# baseline_mu was meant to represent. Computed fresh from whichever priors are currently
# above, so it stays correct across regenerations even if next season's spread differs:
# E[exp(att_mu)]=1.0205, E[exp(def_mu)]=1.0151 -> correction=0.0352 log-units.
def _jensen_correction():
    att_mu = np.array([mu for mu, _ in MANUAL_ATT_PRIORS.values()])
    def_mu = np.array([mu for mu, _ in MANUAL_DEF_PRIORS.values()])
    return np.log(np.exp(att_mu).mean()) + np.log(np.exp(def_mu).mean())


BASELINE_PRIOR_MU_CORRECTED = BASELINE_PRIOR_MU - _jensen_correction()


def scaled_global_priors(games_played: int, ramp_games: int = 10, start_fraction: float = 0.4):
    """(home_adv_prior, baseline_prior) as (mu, sigma) tuples for build_and_sample_model,
    sigma-ramped the same way and over the same window as scaled_priors(). baseline_prior's
    mu is the Jensen-corrected value (see above), not the raw neutral-team BASELINE_PRIOR_MU."""
    scale = sigma_ramp_scale(games_played, ramp_games, start_fraction)
    home_adv_prior = (HOME_ADV_PRIOR_MU, HOME_ADV_PRIOR_SIGMA * scale)
    baseline_prior = (BASELINE_PRIOR_MU_CORRECTED, BASELINE_PRIOR_SIGMA * scale)
    return home_adv_prior, baseline_prior
