"""
manual_priors_2026_27.py — Hand-derived Bayesian priors for the Premier League model.

Generated by priors/2026_27_priors.ipynb from three blended sources:
  1. 2025-26 season posterior (att_str/def_str) for the 17 teams staying up.
  2. This season's Transfermarkt squad value regressed against non-penalty PL
     goals-for/against rate (117 historical team-seasons, R²=0.56 attack /
     0.40 defense), for all 20 teams -- weight 33%.
  3. Championship-form PL forecast (champ_analysis.ipynb's promotion-effect
     model) for Hull, Coventry and Ipswich, in place of a posterior they don't have.

Sources 1/3 get weight 67%, source 2 gets 33%. Promoted sides use
wider sigma=0.5 to reflect greater uncertainty; established PL sides use
sigma=0.3. Relegated (real, penalty-inclusive 2025-26 table): Burnley, West Ham, Wolves.
Sigma=0.4 for teams flipping between Europe and no Europe

Values are the raw (pre-normalisation) mu estimates. The model normalises them
at runtime by subtracting the mean across all teams, ensuring the priors sum to
zero (identifiability constraint).

Usage
-----
    # Mid-season (recommended): sigma ramps from ~half the values below at
    # GW1 up to the full values by GW10 -- see scaled_priors().
    from manual_priors_2026_27 import scaled_priors
    att_priors, def_priors = scaled_priors(games_played)
    _, trace = build_and_sample_model(
        df, n_teams, team_mapping=team_mapping,
        manual_att_priors=att_priors,
        manual_def_priors=def_priors,
    )

    # Season-target sigma directly, no ramp (e.g. preseason projections):
    from manual_priors_2026_27 import MANUAL_ATT_PRIORS, MANUAL_DEF_PRIORS
"""

import numpy as np

# ── Raw priors (pre-normalisation) ───────────────────────────────────────────

_RAW_ATT = {
             'Arsenal': (0.263, 0.3),
         'Aston Villa': (0.025, 0.3),
         'Bournemouth': (0.081, 0.4),
           'Brentford': (0.036, 0.3),
            'Brighton': (0.068, 0.4),
             'Chelsea': (0.202, 0.4),
      'Crystal Palace': (-0.042, 0.3),
             'Everton': (-0.063, 0.3),
              'Fulham': (-0.146, 0.3),
               'Leeds': (-0.068, 0.3),
           'Liverpool': (0.218, 0.3),
            'Man City': (0.338, 0.3),
          'Man United': (0.202, 0.4),
           'Newcastle': (0.051, 0.4),
        'Nottm Forest': (-0.049, 0.4),
          'Sunderland': (-0.245, 0.4),
           'Tottenham': (-0.006, 0.4),
    # Promoted sides — wider prior
                'Hull': (-0.680, 0.5),
            'Coventry': (-0.303, 0.5),
             'Ipswich': (-0.326, 0.5),
}

_RAW_DEF = {
             'Arsenal': (-0.450, 0.3),
         'Aston Villa': (0.037, 0.3),
         'Bournemouth': (0.022, 0.4),
           'Brentford': (-0.021, 0.3),
            'Brighton': (-0.081, 0.4),
             'Chelsea': (-0.092, 0.4),
      'Crystal Palace': (-0.010, 0.3),
             'Everton': (0.050, 0.3),
              'Fulham': (0.040, 0.3),
               'Leeds': (0.046, 0.3),
           'Liverpool': (-0.104, 0.3),
            'Man City': (-0.215, 0.3),
          'Man United': (-0.074, 0.4),
           'Newcastle': (-0.004, 0.4),
        'Nottm Forest': (0.015, 0.4),
          'Sunderland': (0.050, 0.4),
           'Tottenham': (-0.018, 0.4),
    # Promoted sides — wider prior
                'Hull': (0.491, 0.5),
            'Coventry': (0.248, 0.5),
             'Ipswich': (0.241, 0.5),
}


def _normalise(raw):
    """Subtract mean of mus so priors sum to zero (identifiability)."""
    teams = list(raw.keys())
    mus   = np.array([raw[t][0] for t in teams])
    mus  -= mus.mean()
    sigs  = np.array([raw[t][1] for t in teams])
    return {t: (float(mus[i]), float(sigs[i])) for i, t in enumerate(teams)}


MANUAL_ATT_PRIORS = _normalise(_RAW_ATT)
MANUAL_DEF_PRIORS = _normalise(_RAW_DEF)


# ── Early-season sigma ramp ───────────────────────────────────────────────────
# The sigmas above (0.3/0.4/0.5) are a season-long target, calibrated against
# how much a team's strength genuinely varies season-to-season. Applied
# unchanged from GW1, they're too loose relative to how little real match data
# exists yet -- one extreme early scoreline swings a rating almost as much as
# it would mid-season. Empirically swept against 2025-26's actual final
# posterior (see conversation/memory for the sweep): the RMSE-optimal sigma
# rises smoothly from ~half the season target at GW1 to the full target by
# GW10, so ramp sigma over the same window rather than applying the season
# value from kickoff.
def sigma_ramp_scale(games_played: int, ramp_games: int = 10, start_fraction: float = 0.4) -> float:
    """
    Fraction of season-target sigma to use, given games played so far.

    Ramps linearly from `start_fraction` (of the season-target sigma) at zero
    games played, up to 1.0 (full season-target sigma) by `ramp_games` games
    played, then stays at 1.0 for the rest of the season.
    """
    if ramp_games <= 0:
        return 1.0
    progress = min(max(games_played, 0), ramp_games) / ramp_games
    return start_fraction + (1.0 - start_fraction) * progress


def scaled_priors(games_played: int, ramp_games: int = 10, start_fraction: float = 0.4):
    """
    Return (att_priors, def_priors) with sigma scaled per the early-season
    ramp -- mu is untouched. Use this instead of MANUAL_ATT_PRIORS /
    MANUAL_DEF_PRIORS directly when fitting mid-season, so early gameweeks
    aren't overreacting to a handful of results.
    """
    scale = sigma_ramp_scale(games_played, ramp_games, start_fraction)
    att = {t: (mu, sigma * scale) for t, (mu, sigma) in MANUAL_ATT_PRIORS.items()}
    defn = {t: (mu, sigma * scale) for t, (mu, sigma) in MANUAL_DEF_PRIORS.items()}
    return att, defn


# ── Global (home_adv/baseline) priors and their early-season ramp ────────────
# Historical anchor from np_matches, pre-2025/26 -- previously hardcoded directly in
# src/model.py with a fixed sigma and no ramp at all. That's a real gap: these are
# league-wide averages, not team-specific, but load_and_process_data scopes to the
# *current* season only (no cross-season blending), so a handful of early gameweeks means
# a genuinely tiny match sample feeds them too (~20 matches total by GW2 for the whole
# league) -- the same small-sample overreaction risk sigma_ramp_scale() already exists to
# fix for att/def, just previously unaddressed here. Checked empirically before adding this
# (see analysis discussion): PL's season-level average goals shows no clean multi-season
# upward trend (2.70/2.82/2.85/3.28/2.93/2.75 across 2020-21..2025-26) that would justify
# moving the prior *mean* -- a hot first few gameweeks looks like ordinary small-sample
# noise, not a level shift, so only sigma is ramped here, exactly mirroring scaled_priors().
HOME_ADV_PRIOR_MU = np.log(1.17)
HOME_ADV_PRIOR_SIGMA = 0.1
BASELINE_PRIOR_MU = np.log(1.26)
BASELINE_PRIOR_SIGMA = 0.1


def scaled_global_priors(games_played: int, ramp_games: int = 10, start_fraction: float = 0.4):
    """(home_adv_prior, baseline_prior) as (mu, sigma) tuples for build_and_sample_model,
    sigma-ramped the same way and over the same window as scaled_priors()."""
    scale = sigma_ramp_scale(games_played, ramp_games, start_fraction)
    home_adv_prior = (HOME_ADV_PRIOR_MU, HOME_ADV_PRIOR_SIGMA * scale)
    baseline_prior = (BASELINE_PRIOR_MU, BASELINE_PRIOR_SIGMA * scale)
    return home_adv_prior, baseline_prior
